package:
  name: prettyplotlib
  version: !!str 0.1.7

source:
  fn: prettyplotlib-0.1.7.tar.gz
  url: https://pypi.python.org/packages/source/p/prettyplotlib/prettyplotlib-0.1.7.tar.gz
  md5: 85e4d27cefb86d5b2161eff94a77a7bc
  patches:
    # Clear all setuptools dependencies since they are not required, and also they
    # break our recipe when we use matplotlib-nogui package instead of matplotlib.
    - remove-inline-dependencies.patch

build:
  number: 2

requirements:
  build:
    - python
    - nomkl  # [unix]
    - setuptools
    - matplotlib  # [win]
    - matplotlib-nogui  # [unix]
    - brewer2mpl

  run:
    - python
    # To avoid strict dependency to matplotlib or matplotlib-nogui we disable this until "provides"
    # functionality is merged to conda
    #- matplotlib
    - brewer2mpl

test:
  imports:
    - prettyplotlib

  requires:
    - matplotlib  # [win]
    - matplotlib-nogui  # [unix]

about:
  home: http://olgabot.github.io/prettyplotlib
  license: MIT License
