{% set version = "6.1.0" %}

package:
  name: gcc-6
  version: {{ version }}

source:
  fn: gcc-{{ version }}.tar.bz2
  url: http://mirrors.kernel.org/gnu/gcc/gcc-{{ version }}/gcc-{{ version }}.tar.bz2
  md5: 8fb6cb98b8459f5863328380fbf06bd1

build:
  detect_binary_files_with_prefix: true # [not linux32]
  number: 0

requirements:
  build:
    # Dependencies that are required to unpack GCC sources:
    # * tar
    # * bzip2
    # System dependencies that are required to build GCC:
    # * gcc
    # * gcc-c++
    # * make
    # * zip
    # NOTE: Do not make gcc a conda build dependency (you will need to add it to the PATH manually)
    #
    # Other build requirements (https://gcc.gnu.org/install/prerequisites.html):
    - gmp >=4.3.2
    - mpfr >=2.4.2
    - mpc >=0.8.1
    - isl >=0.14,<=0.16.1
  run:
    - gmp >=4.3.2
    - mpfr >=2.4.2
    - mpc >=0.8.1
    - isl >=0.14,<=0.16.1

test:
  commands:
    - gcc --help

about:
  home: http://gcc.gnu.org/
  summary: The GNU Compiler Collection
  license: GPL
