package:
  name: msgpack-c
  version: "1.2.0"

source:
  fn: cpp-1.2.0.tar.bz2
  url: https://github.com/msgpack/msgpack-c/archive/cpp-1.2.0.tar.gz
  md5: feb5cab5d0f18b13c0217644782ede0a

build:
  number: 1

requirements:
  build:
    - cmake

about:
  home: https://github.com/msgpack/msgpack-c
  license: Apache License Version 2.0
  summary: MessagePack implementation for C and C++ / msgpack.org
