package:
  name: msgpack-c
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'cpp-current')[4:] }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

source:
  git_url: https://github.com/msgpack/msgpack-c.git

requirements:
  build:
    - cmake

about:
  home: https://github.com/msgpack/msgpack-c
  license: Apache License Version 2.0
  summary: MessagePack implementation for C and C++ / msgpack.org
