package:
  name: boost_bin_devel
  version: 1.57.0.1
  
requirements:
  run:
    - boost_bin_debug
    - boost_bin   

about:
  home: http://www.salford-systems.com/
  summary: Distribute boost binaries required by other Salford Systems packages. Meta-package assembling all the binaries used for development.
