package:
  name: binutils
  version: 2.25.1

source:
  fn: binutils-2.25.1.tar.bz2
  url: https://ftp.gnu.org/gnu/binutils/binutils-2.25.1.tar.bz2
  sha256: b5b14added7d78a8d1ca70b5cb75fef57ce2197264f4f5835326b0df22ac9f22

build:
  number: 1

requirements:
  build:
    - gcc [linux]

about:
  home: https://www.gnu.org/software/binutils/
  license: GPL
  summary: |
    A set of programming tools for creating and managing binary programs,
    object files, libraries, profile data, and assembly source code.
