package:
  name: msvcrt
  version: 12.0.0.1

about:
  home: http://www.salford-systems.com/
  summary: Distribute Microsoft Visual C++ runtime required by other Salford Systems packages. Package version mathes version of Visual Studio.
