package:
  name: matplotlib-nogui
  version: 1.5.1

source:
  fn: matplotlib-1.5.1.tar.gz
  url: https://github.com/matplotlib/matplotlib/archive/v1.5.1.tar.gz
  md5: b22dc4962f36aab919a7125b3b35953b

requirements:
  build:
    - python
    - setuptools
    - nomkl  # [unix]
    - numpy
    - python-dateutil
    - pkg-config  # [unix]
    - freetype
    - msinttypes  # [win]
    - cycler
    - nose
    - pyparsing
    - pytz
    - tornado
    - libpng  # [unix]
    - zlib  # [win]
  run:
    - python
    - numpy
    - libgcc  # [linux]
    - cycler
    - python-dateutil
    - freetype
    - pytz
    - pyparsing
    - libpng  # [unix]

test:
    imports:
        - matplotlib
        - matplotlib.pyplot

about:
  home: http://matplotlib.org/
  license: PSF-based (http://matplotlib.org/users/license.html)
  summary: Publication quality figures in Python

extra:
  recipe-maintainers:
    - pelson
    - tacaswell
    - JanSchulz
