package:
  name: wtl
  version: 8.1.12085.1

requirements:
    run:
        - atl_vc
  
about:
  home: http://sourceforge.net/projects/wtl/
  summary:  Windows Template Library (WTL) is a C++ library for developing Windows applications and UI components. It extends ATL (Active Template Library) and provides a set of classes for controls, dialogs, frame windows, GDI objects, and more.
