
package:
    name: pcre
    version: 8.39

source:
    url: http://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.39.tar.gz
    sha1: b3aec1f643d9701841e2f9d57ac121a7ff448fc8

build:
    number: 0

requirements:
  build:
    - gcc

  run:
    - libgcc

about:
    home:  http://www.pcre.org/
    license: 3-clause BSD License

