package:
  name: pywebhdfs
  version: !!str 0.3.2

source:
  fn: pywebhdfs-0.3.2.tar.gz
  url: https://pypi.python.org/packages/source/p/pywebhdfs/pywebhdfs-0.3.2.tar.gz
  md5: d61ba79d45598efe4412c8ed947b5e00
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sphinx_rtd_theme = sphinx_rtd_theme:main
    #
    # Would create an entry point called sphinx_rtd_theme that calls sphinx_rtd_theme.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pbr

  run:
    - python
    - requests
    - six

test:
  # Python imports
  imports:
    - pywebhdfs

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/pywebhdfs/pywebhdfs/
  license: Apache License, Version 2.0
  summary: 'Python wrapper for the hadoop WebHDFS Rest API'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
