package:
  name: boost
  version: "1.58.0"

source:
  fn: boost_1_58_0.tar.bz2
  url: http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.bz2

build:
  number: 1000

requirements:
  build:
    - python
    - icu               [unix]
    - bzip2             [unix]
    - libpython         [win]

  run:
    # python dependency is here due to libboost-python library that depends on python version
    - python
    - icu               [unix]

about:
  home: http://www.boost.org/
  license: Boost-1.0

