package:
  name: gmp
  version: 5.1.3

source:
  fn: gmp-5.1.3.tar.bz2
  url: ftp://ftp.gnu.org/gnu/gmp/gmp-5.1.3.tar.bz2

build:
  number: 1

requirements:
  build:
    - m4

test:
  files:
    - test.c

about:
  home: http://gmplib.org/
  license: GPL 3
