package:
  name: sphinxcontrib-mockautodoc
  version: !!str 0.0.1

source:
  fn: sphinxcontrib-mockautodoc-0.0.1dev-20130518.tar.gz
  url: https://pypi.python.org/packages/source/s/sphinxcontrib-mockautodoc/sphinxcontrib-mockautodoc-0.0.1dev-20130518.tar.gz
  md5: d715dff30c74a924b26b7228e6bfe53e
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sphinxcontrib-autoprogram = sphinxcontrib-autoprogram:main
    #
    # Would create an entry point called sphinxcontrib-autoprogram that calls sphinxcontrib-autoprogram.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - sphinx >=0.6

  run:
    - python
    - sphinx >=0.6

test:
  # Python imports
  imports:
    - sphinxcontrib

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://bitbucket.org/birkenfeld/sphinx-contrib
  license: BSD License
  summary: 'Mock imports for build docs without install packages in environment.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
